project_id = "ewmstejympjtlejzoowb"

[functions.telegram-auth]
verify_jwt = false

[functions.create-order]
verify_jwt = false

[functions.telegram-webhook]
verify_jwt = false

[functions.init-admin]
verify_jwt = false

[functions.setup-webhook]
verify_jwt = false
